import React from "react";

// NOTE: This page is designed to be rendered cleanly for Puppeteer PDF generation.
// It relies on a token passed via query params for headless authentication.

export default async function ReportRenderPage({
  params,
  searchParams,
}: {
  params: { id: string; locale: string };
  searchParams: { token: string };
}) {
  const { id } = params;
  const { token } = searchParams;

  // In a real application, you would:
  // 1. Verify the 'token' to ensure the request is authorized by the backend PDF service.
  // 2. Fetch the report execution data using the template ID and verified token context.

  // Mock data for demonstration:
  const reportData = {
    name: "Sample Headcount Report",
    columns: [
      { key: "department", label: "Department" },
      { key: "count", label: "Employee Count" },
    ],
    data: [
      { department: "Engineering", count: 42 },
      { department: "Sales", count: 18 },
      { department: "HR", count: 5 },
    ],
    generatedAt: new Date().toLocaleString(),
  };

  return (
    <div
      className="p-8 max-w-4xl mx-auto bg-white"
      style={{ fontFamily: "sans-serif" }}
    >
      <div className="border-b pb-4 mb-6">
        <h1 className="text-2xl font-bold m-0">{reportData.name}</h1>
        <p className="text-gray-500 text-sm mt-1">
          Generated: {reportData.generatedAt}
        </p>
      </div>

      <table className="w-full border-collapse border border-gray-300">
        <thead>
          <tr className="bg-gray-100">
            {reportData.columns.map((col) => (
              <th
                key={col.key}
                className="border border-gray-300 px-4 py-2 text-left text-sm font-semibold text-gray-700"
              >
                {col.label}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {reportData.data.map((row, idx) => (
            <tr key={idx} className="hover:bg-gray-50">
              {reportData.columns.map((col) => (
                <td
                  key={col.key}
                  className="border border-gray-300 px-4 py-2 text-sm text-gray-700"
                >
                  {row[col.key as keyof typeof row]}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mt-8 text-center text-xs text-gray-400">
        <p>Generated by Nurox ERP Reporting Engine</p>
      </div>
    </div>
  );
}
