import { MigrationInterface, QueryRunner } from 'typeorm';

export class EnableRLS1779899000000 implements MigrationInterface {
  private readonly tables = [
    'accounting_periods',
    'accounts',
    'activity_logs',
    'advance_salary_requests',
    'api_keys',
    'applications',
    'approval_matrices',
    'approval_steps',
    'approval_workflows',
    'asset_assignments',
    'asset_categories',
    'asset_maintenances',
    'assets',
    'attendance_records',
    'audit_logs',
    'auto_number_sequences',
    'bank_accounts',
    'bank_transactions',
    'batches',
    'bills',
    'bins',
    'bom_items',
    'boms',
    'branches',
    'budgets',
    'candidates',
    'change_requests',
    'chart_of_accounts',
    'chat_channels',
    'chat_messages',
    'clearance_checklists',
    'compensatory_leaves',
    'consent_logs',
    'contacts',
    'cost_centers',
    'credit_notes',
    'custom_field_definitions',
    'custom_field_values',
    'deals',
    'debit_notes',
    'delivery_orders',
    'departments',
    'designations',
    'document_folders',
    'document_versions',
    'documents',
    'employee_bonuses',
    'employee_loans',
    'employees',
    'employment_history',
    'enps_surveys',
    'exit_interviews',
    'expense_claims',
    'fuel_logs',
    'goods_issue_items',
    'goods_issues',
    'goods_receipt_items',
    'goods_receipts',
    'goods_return_items',
    'goods_returns',
    'grades',
    'grns',
    'handbooks',
    'holidays',
    'interviews',
    'invoices',
    'job_requisitions',
    'journal_entries',
    'kb_articles',
    'leads',
    'leave_requests',
    'login_events',
    'memberships',
    'milestones',
    'notification_preferences',
    'notifications',
    'offer_letters',
    'okr_checkins',
    'onboarding_checklists',
    'onboarding_templates',
    'payroll_audits',
    'payroll_runs',
    'performance_reviews',
    'petty_cash_funds',
    'pinned_reports',
    'pip_action_plans',
    'pos_orders',
    'pos_sessions',
    'pricelists',
    'probation_records',
    'product_variants',
    'production_logs',
    'products',
    'profile_change_requests',
    'project_risks',
    'project_templates',
    'projects',
    'purchase_orders',
    'purchase_requests',
    'quotations',
    'racks',
    'recurring_invoices',
    'recurring_journals',
    'regularization_requests',
    'report_schedules',
    'report_templates',
    'resignations',
    'review_feedback',
    'rfqs',
    'roles',
    'salary_history',
    'salary_revisions',
    'salary_structures',
    'sales_orders',
    'serial_numbers',
    'shift_assignments',
    'shifts',
    'skill_catalog',
    'skills',
    'stock_count_items',
    'stock_counts',
    'stock_movements',
    'stock_transfer_items',
    'stock_transfers',
    'succession_plans',
    'system_announcements',
    'system_notifications',
    'tasks',
    'tax_configurations',
    'tax_filing_exports',
    'tax_rates',
    'tax_rules',
    'terminations',
    'ticket_messages',
    'ticket_slas',
    'tickets',
    'time_logs',
    'timesheets',
    'training_courses',
    'trainings',
    'transfer_requests',
    'trip_logs',
    'uom_conversions',
    'uom_groups',
    'user_dashboard_widgets',
    'user_preferences',
    'user_sessions',
    'users',
    'vehicles',
    'vendor_bills',
    'vendor_evaluations',
    'vendors',
    'warehouses',
    'webhook_configs',
    'webhook_deliveries',
    'webhook_delivery_logs',
    'webhook_endpoints',
    'work_orders',
    'workcenters',
    'workflow_rules',
    'working_calendars',
    'zones',
  ];

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const table of this.tables) {
      await queryRunner.query(
        `ALTER TABLE "${table}" ENABLE ROW LEVEL SECURITY;`,
      );
      await queryRunner.query(
        `ALTER TABLE "${table}" FORCE ROW LEVEL SECURITY;`,
      );
      await queryRunner.query(
        `DROP POLICY IF EXISTS tenant_isolation_policy ON "${table}";`,
      );
      await queryRunner.query(`
        CREATE POLICY tenant_isolation_policy ON "${table}"
        USING (tenant_id = current_setting('app.current_tenant_id')::uuid)
        WITH CHECK (tenant_id = current_setting('app.current_tenant_id')::uuid);
      `);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const table of this.tables) {
      await queryRunner.query(
        `ALTER TABLE "${table}" DISABLE ROW LEVEL SECURITY;`,
      );
      await queryRunner.query(
        `DROP POLICY IF EXISTS tenant_isolation_policy ON "${table}";`,
      );
    }
  }
}
