import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQueryWithReauth } from "@/lib/api-client";

/**
 * Unified Base API for Nurox ERP.
 * All feature-specific APIs should use baseApi.injectEndpoints().
 */
export const baseApi = createApi({
  reducerPath: "api",
  baseQuery: baseQueryWithReauth,
  tagTypes: [
    "Employee",
    "Department",
    "Position",
    "Designation",
    "Grade",
    "History",
    "Performance",
    "Training",
    "Skill",
    "TrainingCourse",
    "SkillCatalog",
    "ENPS",
    "Handbook",
    "Succession",
    "Payroll",
    "PayrollStructure",
    "Payslip",
    "TaxConfig",
    "Leave",
    "LeaveBalance",
    "LeaveType",
    "Attendance",
    "Shift",
    "Holiday",
    "Candidate",
    "Application",
    "Interview",
    "Offer",
    "Job",
    "Onboarding",
    "OnboardingTemplate",
    "Invoice",
    "Bill",
    "Journal",
    "ChartOfAccount",
    "BankStatement",
    "Product",
    "Warehouse",
    "Stock",
    "StockMovement",
    "PurchaseOrder",
    "PurchaseRequest",
    "Vendor",
    "GRN",
    "RFQ",
    "Lead",
    "Opportunity",
    "Customer",
    "SalesOrder",
    "Quotation",
    "Project",
    "Task",
    "Timesheet",
    "Milestone",
    "Asset",
    "AssetCategory",
    "Depreciation",
    "Maintenance",
    "Document",
    "Folder",
    "Notification",
    "Announcement",
    "AuditLog",
    "Dashboard",
    "Report",
    "User",
    "Preference",
    "DashboardWidget",
    "Role",
    "Permission",
    "Tenant",
    "Branch",
    "Module",
    "Calendar",
    "Setting",
    "Subscription",
    "Invoice_Billing",
    "Ticket",
    "KnowledgeBase",
    "Channel",
    "Message",
    "WorkOrder",
    "BOM",
    "Vehicle",
    "Delivery",
    "Route",
    "TaxRate",
    "TaxReturn",
  ],
  endpoints: () => ({}),
});
